# Generated by Django 5.2.1 on 2025-05-31 10:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_remove_stock_date_fetched_remove_stock_ticker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='price',
        ),
        migrations.AddField(
            model_name='stock',
            name='date_fetched',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
